FROM ubuntu

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install gcc -y
RUN apt-get install make -y
RUN apt-get install vim -y
RUN apt-get install git -y

#docker build -t ub .
#docker run -it --rm ub
